/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import tools.Connections;



/**
 *
 * @author Rizky
 */
public class MainView extends javax.swing.JFrame {
    private Connection connection;
    
    
    JasperReport Jasrep;
    JasperPrint Jaspri;
    Map param = new HashMap();
    JasperDesign JasDes;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.connection = new Connections().getConnection();
    }

    public MainView(Connection connection) {
        this.connection = connection;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskHR = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRegion = new javax.swing.JMenuItem();
        mnLocation = new javax.swing.JMenuItem();
        mnCountry = new javax.swing.JMenuItem();
        mnReportLocation = new javax.swing.JMenu();
        mnRegionReport = new javax.swing.JMenuItem();
        mnLocationReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR SYSTEM");

        dskHR.setBackground(new java.awt.Color(204, 204, 255));
        dskHR.setPreferredSize(new java.awt.Dimension(1277, 728));

        javax.swing.GroupLayout dskHRLayout = new javax.swing.GroupLayout(dskHR);
        dskHR.setLayout(dskHRLayout);
        dskHRLayout.setHorizontalGroup(
            dskHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1457, Short.MAX_VALUE)
        );
        dskHRLayout.setVerticalGroup(
            dskHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mnRegion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnRegion.setText("Region");
        mnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegionActionPerformed(evt);
            }
        });
        jMenu1.add(mnRegion);

        mnLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnLocation.setText("Location");
        mnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLocationActionPerformed(evt);
            }
        });
        jMenu1.add(mnLocation);

        mnCountry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnCountry.setText("Country");
        mnCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCountryActionPerformed(evt);
            }
        });
        jMenu1.add(mnCountry);

        jMenuBar1.add(jMenu1);

        mnReportLocation.setText("Report");

        mnRegionReport.setText("Region");
        mnRegionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegionReportActionPerformed(evt);
            }
        });
        mnReportLocation.add(mnRegionReport);

        mnLocationReport.setText("Location");
        mnLocationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLocationReportActionPerformed(evt);
            }
        });
        mnReportLocation.add(mnLocationReport);

        jMenuBar1.add(mnReportLocation);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskHR, javax.swing.GroupLayout.PREFERRED_SIZE, 1457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskHR, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegionActionPerformed
        // TODO add your handling code here:
        RegionsView regions = new RegionsView();
        regions.show();
        dskHR.add(regions);
    }//GEN-LAST:event_mnRegionActionPerformed

    private void mnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLocationActionPerformed
        // TODO add your handling code here:
        LocationsView locations = new LocationsView();
        locations.show();
        dskHR.add(locations);
    }//GEN-LAST:event_mnLocationActionPerformed

    private void mnCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCountryActionPerformed
        // TODO add your handling code here:
        Country country = new Country();
        country.show();
        dskHR.add(country);
    }//GEN-LAST:event_mnCountryActionPerformed

    private void mnRegionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegionReportActionPerformed
        // TODO add your handling code here:
         ReportView report = new ReportView("Region");
        report.show();
        dskHR.add(report);
//        try {
//            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
//            Connection konek = this.connection;
////            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "SYSTEM", "rizky");
//            File report = new File("./src/reports/ReportRegion.jrxml");
//            JasDes = JRXmlLoader.load(report);
//            JasperReport JasRep = JasperCompileManager.compileReport(JasDes);
//            JasperPrint JasPri = JasperFillManager.fillReport(JasRep, param, konek);
//            JasperViewer.viewReport(JasPri, false);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_mnRegionReportActionPerformed

    private void mnLocationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLocationReportActionPerformed
        // TODO add your handling code here:
        ReportView report = new ReportView("Location");
        report.show();
        dskHR.add(report);
//        try {
//            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
//            Connection konek = this.connection;
////            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "SYSTEM", "rizky");
//            File report = new File("./src/reports/ReportLocation.jrxml");
//            JasDes = JRXmlLoader.load(report);
//            JasperReport JasRep = JasperCompileManager.compileReport(JasDes);
//            JasperPrint JasPri = JasperFillManager.fillReport(JasRep, param, konek);
//            JasperViewer.viewReport(JasPri, false);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_mnLocationReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskHR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnCountry;
    private javax.swing.JMenuItem mnLocation;
    private javax.swing.JMenuItem mnLocationReport;
    private javax.swing.JMenuItem mnRegion;
    private javax.swing.JMenuItem mnRegionReport;
    private javax.swing.JMenu mnReportLocation;
    // End of variables declaration//GEN-END:variables
}
